# Site settings
title: Meetthekosmos.com
description: > # this means to ignore newlines until "baseurl:"
  Photographer and storyteller from Saint-Petersburg, Russia. Available worldwide.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social
email: tashakosmos@gmail.com
facebook: http://facebook.com/tasha.konkina
vk: http://vk.com/tashakosmos
instagram: http://instagram.com/tashakosmos

# Build settings
markdown: kramdown

# Develop
version: v0.2.3
